inherit_gem: { servactory-rubocop: rubocop-gem.yml }

Style/Documentation:
  Enabled: false

################################################################################

RSpec/ExampleLength:
  Max: 200
