name: Test

on:
  push:
    branches:
      - main
      - v1-stable
  pull_request:
    branches:
      - main
      - v1-stable
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
#  generate-seed:
#    name: Generate random seed
#    runs-on: ubuntu-latest
#    outputs:
#      seed: ${{ steps.seed_generator.outputs.seed }}
#    steps:
#      - id: seed_generator
#        run: echo "::set-output name=seed::$(shuf -i 0-99999 -n 1)"

  rspec:
    name: Ruby ${{matrix.ruby-version}} (${{ matrix.gemfile }})
    runs-on: ubuntu-latest
#    needs:
#      - generate-seed
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rails_5.1
          - rails_5.2
          - rails_6.0
          - rails_6.1
          - rails_7.0
          - rails_7.1
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

      - name: RSpec
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
        run: bundle exec rspec # --seed ${{ needs.generate-seed.outputs.seed }}
